version: '3'

services:
  dolphin-admin-db:
    image: postgres:15
    container_name: dolphin-admin-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  # dolphin-admin-api:
  #   container_name: dolphin-admin-api
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     - dolphin-admin-db
