name: CD

on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - completed

jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # - name: â˜ï¸ Checkout Repository
      #   uses: actions/checkout@v3

      # - name: ğŸ”§ Install pnpm
      #   uses: pnpm/action-setup@v2

      # - name: ğŸ”§ Use Node.js 18
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     registry-url: https://registry.npmjs.org/
      #     cache: pnpm

      # - name: ğŸ“¦ Install monorepo deps
      #   run: pnpm i

      # - name: ğŸš€ Build front-end project
      #   run: pnpm web:build

      - name: ğŸ”§ Setup SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: sh bin/deploy.sh
