name: CD

on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - completed

jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”§ Check CI status
        uses: actions/github-script@v5
        with:
          script: |
            const { data: { conclusion } } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            if (conclusion !== 'success') {
              console.log('CI workflow failed, stopping CD workflow.');
              process.exit(1);
            }

      - name: â˜ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ”§ Install pnpm
        uses: pnpm/action-setup@v2

      - name: ğŸ”§ Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: ğŸ“¦ Install monorepo deps
        run: pnpm i

      - name: ğŸš€ Build front-end project
        run: pnpm web:build

      - name: ğŸ”§ Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: sh bin/deploy.sh
